[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "DGxn19P5Lj54Y8uctMtRTndF3o7h4iZWza5FDSrrzmVG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/vardaan/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
